export const UPDATE_TRANSACTION_LIST = "UPDATE_TRANSACTION_LIST";
export const UPDATE_TRANSACTION_SELECTED = "UPDATE_TRANSACTION_SELECTED";
export const OPEN_MODAL_POPUP = "OPEN_MODAL_POPUP";
export const CLOSE_MODAL_POPUP = "CLOSE_MODAL_POPUP";
export const LOADNG_SPINNER = "LOADNG_SPINNER";