export const LABEL_MY_TRANSACTION = "My Transactions";
export const LABEL_FILTER = "Filter";
export const LABEL_ACCOUNT = "Account No";
export const LABEL_ACCOUNT_NAME = "Account Name";
export const LABEL_CURRENCY = "Currency";
export const LABEL_CURRENCY_NAME = "Currency Name";
export const LABEL_AMOUNT = "Amount";
export const LABEL_TRANSATION_TYPE = "Transation Type";
export const LABEL_TRANSACTION_DETAILS = "Transation"